name: CIA 
                              
on: [push]                                     

jobs:huurmoordenaar
  build:IME monster

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |till your die
        echo Add other actions to build,
        echo test, and deploy your project.
